---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/experiment2019/saliency_schizophrenia5")
library(readr)
# ランダム効果に含めることで、疑似反復に対応したANOVA
library(lme4) #lmer関数を含むパッケージ
library(lmerTest)
```

readrのread_csvを使用。 
https://cran.r-project.org/web/packages/readr/readr.pdf
col_factor(levels = NULL, ordered = FALSE, include_na = FALSE)
TimeM, SaccMでは ordered TRUE にしておく

```{r}
id <- 1:334
id <- factor(id)
sac <- 1:16
sac <- factor(sac)

plotdata2 <- read_csv("plotdata_tidy_20220126b.csv",
            col_types = cols(
              subjectM = col_factor(levels = c("0", "1")),
              SaccM = col_factor(levels = levels(sac), ordered = TRUE),
              idM = col_factor(levels = levels(id))
              ))

plotdataSac <- read_csv("plotdata_tidy_20220126b.csv")
plotdata2$SaccM2 <- log(plotdataSac$SaccM)
plotdata2
```

Full model, random slope and intercept model (SaccM2|idM)
```{r}
lmer1.m <- lmer(Sal~subjectM+SaccM2+(SaccM2|idM), data = plotdata2)
lmer2.m <- lmer(Sal~subjectM*SaccM2+(SaccM2|idM), data = plotdata2)
anova(lmer1.m)
anova(lmer2.m)
```

Luminance model, random slope and intercept model (SaccM2|idM)
```{r}
lmer1L.m <- lmer(SalL~subjectM+SaccM2+(SaccM2|idM), data = plotdata2)
lmer2L.m <- lmer(SalL~subjectM*SaccM2+(SaccM2|idM), data = plotdata2)
anova(lmer1L.m)
anova(lmer2L.m)
```

Color model, random slope and intercept model (SaccM2|idM)
```{r}
lmer1C.m <- lmer(SalC~subjectM+SaccM2+(SaccM2|idM), data = plotdata2)
lmer2C.m <- lmer(SalC~subjectM*SaccM2+(SaccM2|idM), data = plotdata2)
anova(lmer1C.m)
anova(lmer2C.m)
```

Orientation model, random slope and intercept model (SaccM2|idM)
```{r}
lmer1O.m <- lmer(SalO~subjectM+SaccM2+(SaccM2|idM), data = plotdata2)
lmer2O.m <- lmer(SalO~subjectM*SaccM2+(SaccM2|idM), data = plotdata2)
anova(lmer1O.m)
anova(lmer2O.m)
```
